# Generated by Django 3.0.2 on 2020-03-22 02:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_recomender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
