# Generated by Django 3.0.2 on 2020-03-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_recomender', '0002_query_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField()),
                ('coffee', models.CharField(max_length=30)),
                ('evaluation', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='query',
            old_name='date',
            new_name='query_date',
        ),
    ]
